### ISSUE TITLE
TouchImageView & Volley  NetworkImageView

### ISSUE THREAD

**Issue by tasosno1** [MikeOrtiz/TouchImageView#136]
Hi,

Thank you for your Library it works great.

I'm Using a ViewPager in my project and so far i found Volley to be very good at loading in the images for the individual pages.

Volley needs <code>com.android.volley.toolbox.NetworkImageView</code> and  TouchImageView needs <code>com.android.touch.TouchImageView</code> for ImageView 

Well my question is how i do combine both of these 

I cant get the zoom to work when using  Volley

Or i can get the zoom to work by loading in standard bitmaps but  swapping pages is slow with that and i'm not that experienced with Bitmaps cashing etc hence why i need volley for the easy of use.

any way to get both of these to work together.

My Pager code

![capture](https://cloud.githubusercontent.com/assets/9547308/9409733/310c7058-4825-11e5-95cb-4a3ed9290940.PNG)

Thanks

**Comment by tasosno1** [comment]
Screw using volley for this, viewPager loading img's and zooming i mean. I combined uni image loader and the touch zoom.

**Comment by pranav-g10** [comment]
In case someone's is still wondering, the problem boils down to this:
Volley's NetworkImageView doesn't load the URL if the imageView is of 0 width and height and TouchImageView sets the measured dimensions as 0 if there is no drawable present. So the 2 cancel each other out and the image is never loaded.

To fix it, make TouchImageView extend NetworkImageView, instead of ImageView,
and in it's onMeasure override, change the null-check condition from the existing `setMeasuredDimension(0, 0)` to the following:

        if (drawable == null || drawable.getIntrinsicWidth() == 0 || drawable.getIntrinsicHeight() == 0) {
            if (getLayoutParams().width == ViewGroup.LayoutParams.MATCH_PARENT
                    && getLayoutParams().height == ViewGroup.LayoutParams.MATCH_PARENT) {
                viewWidth = MeasureSpec.getSize(widthMeasureSpec);
                viewHeight = MeasureSpec.getSize(heightMeasureSpec);
            }
            super.onMeasure(widthMeasureSpec, heightMeasureSpec);
            return;
        }

This issue is specific to when the view is expected to be MATCH_PARENT. I haven't tried out WRAP_CONTENT or fixed sized view's but theoretically the problem shouldn't happen there at all.

**Comment by tasosno1** [comment]
Makes sence, well done :)

**Comment by SanPinto** [comment]
@pranav-g10 , Your suggestion worked for me too. Thank you
