### ISSUE TITLE
no image on startup

### ISSUE THREAD

**Issue by farble1670** [MikeOrtiz/TouchImageView#15]
image is blank. i'm using this image,
https://www.google.com/images/srpr/logo3w.png

if i comment out the code in onMeasure() after the "Center the image" comment, the image shows, but perhaps the bottom 20% of the image is truncated. i don't know how / if this is related to the blank image problem.

sorry to file a bug, i wanted to just ask you about it but i didn't know how to accomplish that.

**Comment by iori57** [comment]
Seems that this issue was created 4 years ago but I am seeing this now. In certain layout it works but in certain layout it just shows blank with no image. Commenting out setImageMatrix(matrix) in the last line of onMeasure() does make the image appear but it is pushed all the way to the left while zooming behavior were all broken - zooming causes the image to fly to the bottom right hand side and cannot be reset.

Still trying to figure out why it works for one layout but not the other, although in both I am also using LinearLayout, setting the TouchImageView to have height of 0dp and layout_weight of 1 to have it span the remaining space.
