### ISSUE TITLE
Visibility problem when used in a ViewPager

### ISSUE THREAD

**Issue by psohm** [MikeOrtiz/TouchImageView#152]
I use the component with the android pdf API.
it works well when I use it in a fragment embedded in an activity.

but if I embed the fragment within a ViewPager, it is totally blank (the color of the background) but if I zoom / unzoom, the component is shown.
the only workaround I found is to change the visibility of the TouchImageView to GONE and then make it VISIBLE again

do you have any better workaround / solution ?

best regards

**Comment by iori57** [comment]
I am facing similar issue, with blank imageview being shown until I zoom/unzoom. Setting the visibility to GONE and VISIBLE again doesn't work for my case so maybe our root cause is different as I am not using a ViewPager.

My problem was solved using the fix suggested in this issue: #125 
You might want to give it a try and see if it works for your case.

**Comment by psohm** [comment]
a huge thank you
it's sad that the code doesn't include that fix

**Comment by CoolMind** [comment]
Thanks, #125 helped.
