### ISSUE TITLE
can not display a long image

### ISSUE THREAD

**Issue by yilylong** [MikeOrtiz/TouchImageView#198]
can not display a super long image ,you can test with  a long image .

**Comment by hannesa2** [comment]
What's about to show me an example ? Best as running source code (eg as PR), to see what's **not display** mean

**Comment by yilylong** [comment]
you can use this picture test [https://raw.githubusercontent.com/yilylong/ImageResource/master/large_img.jpg](url)

**Comment by hannesa2** [comment]
I see, you save your time and let me investigate what could be wrong instead of explaining it

>  to see what's **not display** mean

![bigImage](https://user-images.githubusercontent.com/3314607/54806769-55761080-4c7b-11e9-8480-288d0d2820cf.gif)

On the first view, I found nothing wrong.
If you see an improvment/bug/missing feature I can tell you, that we accept pull requests

**Comment by yilylong** [comment]
all right ,i change another test mobile it work well. but the first mobile it can not display 
![large_image](https://user-images.githubusercontent.com/5047329/54808095-1d41f280-4cba-11e9-92d5-b32d6d4b9e5f.gif)
![mobile](https://user-images.githubusercontent.com/5047329/54808432-2f706080-4cbb-11e9-9f3a-2df0899144c2.jpg)

by the way i don't want waste your time

**Comment by hannesa2** [comment]
Did you found the issue ?
