### ISSUE TITLE
JCenter shutdown - plans to upload to Maven central?

### ISSUE THREAD

**Issue by BillyLuisNeedham** [MikeOrtiz/TouchImageView#374]
We love your library! However, AppCenter is no longer supporting jCenter for gradle packages (see: https://blog.gradle.org/jcenter-shutdown)).

Are there any plans to upload to Maven central?

https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by hannesa2** [comment]
I've nothing against it, but I only easy simple to use jitpack.io so I will do nothing.
Feel free to make it, but the handling of credentials is not that easy, because I can't access settings tab.

**Comment by hannesa2** [comment]
If you want it, please make a pull request

**Comment by vanniktech** [comment]
@hannesa2 so you're saying you have push access but can't access the settings tabs? Is @MikeOrtiz still around to enter the credentials and apply for a group id?

**Comment by hannesa2** [comment]
I do only the tasks to keep this repository alive and I was not granted to access to settings tab. 
All other is out of my control.

**Comment by hannesa2** [comment]
Since a long time ago, the owner is no more active and never had in mind of a relay race to keep it alive over long time. eg with a second maintainer who can access settings 

<img width="899" alt="image" src="https://user-images.githubusercontent.com/3314607/133764553-f3de9671-f8cc-42c3-9402-22dc9f7c917b.png">
